package org.ikasan.studio.boot.firstflow;

import org.ikasan.builder.BuilderFactory;
import org.ikasan.spec.component.endpoint.Consumer;
import org.ikasan.spec.component.endpoint.Producer;
import org.ikasan.spec.component.transformation.Converter;
import org.myApp.firstflow.MyXToYConverter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;

import javax.annotation.Resource;

/**
 * The component factory defines the details of the components and their configuration.
 * <p>
 * This file is auto-generated by Ikasan Studio, do no edit.
 */
@Configuration
public class ComponentFactory {
    @Value("${module.name}")
    private String moduleName;

    @Resource
    BuilderFactory builderFactory;

    @Resource
    MyXToYConverter myXToYConverter;

    public Consumer getTheEventConsumerForX() {
        return builderFactory.getComponentBuilder().eventGeneratingConsumer()
                .build();
    }

    public Converter getMyXToYConverter() {
        return myXToYConverter;
    }

    public Producer getTheYProducer() {
        return builderFactory.getComponentBuilder().logProducer()
                .build();
    }
}