package org.ikasan.studio.boot.firstflow;

import org.ikasan.builder.BuilderFactory;
import org.ikasan.builder.FlowBuilder;
import org.ikasan.builder.ModuleBuilder;
import org.ikasan.spec.flow.Flow;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * The flow is the container for the components.
 * <p>
 * Some details of the components are defined here, but the majority of the configuration for components is delegated
 * to the ComponentFactory
 * <p>
 * This file is auto-generated by Ikasan Studio, do no edit.
 */
@Component
public class FirstFlow {
    @Value("${module.name}")
    private String moduleName;

    @Resource
    BuilderFactory builderFactory;

    @Resource
    ComponentFactory componentFactory;

    @Bean
    public Flow getFirstFlow() {
        ModuleBuilder moduleBuilder = builderFactory.getModuleBuilder(moduleName);
        FlowBuilder flowBuilder = moduleBuilder.getFlowBuilder("first flow");

        Flow firstFlow = flowBuilder
                .consumer("The event consumer for X",
                        componentFactory.getTheEventConsumerForX())
                .converter("My x to y converter",
                        componentFactory.getMyXToYConverter())
                .producer("The y producer",
                        componentFactory.getTheYProducer()).build();
        return firstFlow;
    }
}