package org.ikasan.studio.boot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/**
 * This is the Spring boot start class.
 * This file is auto-generated by Ikasan Studio, do no edit.
 */
@SpringBootApplication
@ComponentScan({"org.ikasan.studio.boot", "org.myApp"})
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}