package org.ikasan.studio.boot;

import org.ikasan.builder.BuilderFactory;
import org.ikasan.builder.ModuleBuilder;
import org.ikasan.builder.component.ComponentBuilder;
import org.ikasan.spec.module.Module;
import org.ikasan.studio.boot.firstflow.FirstFlow;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportResource;

import javax.annotation.Resource;

/**
 * The module config class defines details of the modules and identifies the flows but should not contain details
 * of the components in each flow.
 * <p>
 * This file is auto-generated by Ikasan Studio, do no edit.
 */
@Configuration("ModuleFactory")
@ImportResource({
        "classpath:h2-datasource-conf.xml",
        "classpath:ikasan-transaction-pointcut-ikasanMessageListener.xml"
})
public class ModuleConfig {
    @Value("${module.name}")
    private String moduleName;

    @Resource
    BuilderFactory builderFactory;
    @Resource
    FirstFlow firstFlow;

    @Bean
    public Module myModule() {
        ModuleBuilder moduleBuilder = builderFactory.getModuleBuilder(moduleName);

        ComponentBuilder componentBuilder = builderFactory.getComponentBuilder();

        Module module = moduleBuilder
                .addFlow(firstFlow.getFirstFlow())
                .build();
        return module;
    }

}